Repository oil-rope/oil-and-rope, pull requests merged in 2020-04, with the labels that each got.

#21 OAR-0024 - Implement Calendar
  .travis.yml
  frontend/src/components/App.js
  frontend/src/components/BootstrapButton.js
  frontend/src/components/calendar/Calendar.jsx
  frontend/src/components/calendar/__test__/calendar.test.js
  frontend/src/components/calendar/main.scss
  frontend/src/index.js
  frontend/static/frontend/main.js
  frontend/templates/frontend/index.html
  package-lock.json
  package.json
  webpack.config.js
Labels: enhancement

#22 OAR-0023 - Setup documentation for linux
  README.md
Labels: documentation

#26 OAR-0027 - Make local_settings.py visible
  README.md
  oilandrope/dev_settings.py
  oilandrope/heroku_settings.py
  runtests.py
  setup.cfg
Labels: bug, documentation

#24 OAR-0020 - Bug fixed!
  registration/forms.py
  tests/registration/test_forms.py
  tests/registration/test_views.py
Labels: bug

#27 OAR-0028 - Improve Mobile Design
  core/templates/core/includes/menu.html
  registration/forms.py
  registration/templates/registration/login.html
  registration/templates/registration/register.html
Labels: enhancement

#28 OAR-0030 - Fix Documentation
  README.md
Labels: bug

#25 OAR-0014 - Resend Email View
  registration/forms.py
  registration/templates/registration/resend_email.html
  registration/urls.py
  registration/views.py
  tests/registration/test_forms.py
  tests/registration/test_views.py
Labels: bug, enhancement

#20 OAR-0011 - Discord Bot Integration
  .babelrc
  .editorconfig
  .gitignore
  .travis.yml
  Aptfile
  Procfile
  bot/__init__.py
  bot/bot.py
  bot/categories.py
  bot/config.py
  bot/consumers.py
  bot/exceptions.py
  bot/management/commands/runbot.py
  bot/models.py
  bot/routing.py
  bot/urls.py
  bot/utils.py
  chat/models.py
  core/__init__.py
  core/checks.py
  core/consumers.py
  core/models.py
  core/templates/core/layout.html
  dynamic_menu/context_processors.py
  dynamic_menu/models.py
  frontend/src/components/buttons/discord/UserCheckButton/UserCheckButton.jsx
  frontend/src/components/buttons/discord/UserCheckButton/__test__/UserCheckButton.test.js
  frontend/src/components/calendar/Calendar.jsx
  frontend/src/components/calendar/__test__/calendar.test.js
  frontend/src/index.js
  frontend/src/renderCalendar.js
  frontend/src/renderUserCheckButton.js
  frontend/static/frontend/main.js
  frontend/templates/frontend/index.html
  oilandrope/asgi.py
  oilandrope/routing.py
  oilandrope/settings.py
  oilandrope/urls.py
  package-lock.json
  package.json
  registration/forms.py
  registration/models.py
  registration/templates/registration/register.html
  registration/views.py
  requirements/requirements-base.txt
  requirements/requirements-develop.txt
  run.py
  runtests.py
  setup.cfg
  sheet/models.py
  tests/bot/test_config.py
  tests/bot/test_consumers.py
  tests/conftest.py
  tests/core/test_consumers.py
  tests/registration/test_forms.py
  tests/registration/test_views.py
  webpack.config.js
Labels: enhancement

#23 OAR-0022 - Added meta data for better presentation
  core/context_processors.py
  core/templates/core/includes/opengraph_protocol.html
  core/templates/core/layout.html
  package.json
Labels: enhancement

#30 OAR-44 - Make proyect more accesible for testers
  .editorconfig
  bot/routing.py
  bot/urls.py
  compose/channels/command.sh
  compose/django/Dockerfile
  compose/django/command.sh
  compose/django/entrypoint.sh
  compose/nginx/conf.d/oilandrope.conf
  docker-compose.yml
  oilandrope/routing.py
  oilandrope/settings.py
  oilandrope/urls.py
  registration/forms.py
  requirements.txt
  requirements/requirements-base.txt
Labels: enhancement

#29 OAR-25 - Complete ~90% of Coverage
  .github/workflow/deploy.yml
  .github/workflow/main.yml
  .gitignore
  .travis.yml
  bot/bot.py
  bot/categories.py
  bot/config.py
  bot/models.py
  bot/utils.py
  compose/django/Dockerfile
  core/checks.py
  core/context_processors.py
  core/templates/core/layout.html
  dynamic_menu/__init__.py
  dynamic_menu/context_processors.py
  dynamic_menu/management/commands/load_menu.py
  frontend/src/components/buttons/discord/user-check-button/UserCheckButton.jsx
  frontend/src/components/buttons/discord/user-check-button/__test__/UserCheckButton.test.js
  frontend/src/components/calendar/Calendar.jsx
  frontend/src/components/calendar/__test__/calendar.test.js
  frontend/src/components/calendar/main.scss
  frontend/src/components/loader/Loader.jsx
  frontend/src/components/loader/__test__/Loader.test.js
  frontend/src/renderCalendar.js
  frontend/src/renderUserCheckButton.js
  frontend/static/frontend/fullcalendar/core/main.min.css
  frontend/static/frontend/fullcalendar/daygrid/main.min.css
  frontend/static/frontend/fullcalendar/timegrid/main.min.css
  frontend/templates/frontend/index.html
  oilandrope/urls.py
  package-lock.json
  package.json
  registration/forms.py
  registration/models.py
  registration/permissions.py
  registration/views.py
  requirements/requirements-develop.txt
  setup.cfg
  tests/bot/helpers/mocks.py
  tests/bot/test_bot.py
  tests/bot/test_categories.py
  tests/bot/test_models.py
  tests/bot/test_utils.py
  tests/bot/test_viewsets.py
  tests/conftest.py
  tests/core/management/commands/__init__.py
  tests/core/management/commands/test_check.py
  tests/core/test_access.py
  tests/core/test_checks.py
  tests/core/test_context_processors.py
  tests/core/test_views.py
  tests/dynamic_menu/management/commands/_init__.py
  tests/dynamic_menu/management/commands/test_load_menu.py
  tests/dynamic_menu/test_context_processors.py
  tests/dynamic_menu/test_init.py
  tests/dynamic_menu/test_load_menu.py
  tests/dynamic_menu/test_models.py
  tests/registration/test_models.py
  tests/tmpi9uulyvh.json
  webpack.config.js
Labels: enhancement

#31 OAR-83 - Change Icon
  .travis.yml
  bot/bot.py
  bot/models.py
  core/static/img/oilandrope_color.png
  core/static/img/oilandrope_dark.png
  core/templates/core/includes/menu.html
  runtests.py
Labels: enhancement
